apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
        service: reverse-proxy
    spec:
      containers:
      - image: ctala/reverse-proxy
        name: reverse-proxy
        imagePullPolicy: Always           
        ports:
        - containerPort: 8090
      restartPolicy: Always